# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 07:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Running'), ('F', 'Failure'), ('S', 'Success')], default='P', max_length=1)),
                ('signature', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='cq.Task')),
                ('previous', models.ManyToManyField(related_name='_task_previous_+', to='cq.Task')),
            ],
            options={
                'ordering': ('-submitted',),
            },
        ),
    ]
