# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0002_add_repeating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('Y', 'Retry'), ('Q', 'Queued'), ('R', 'Running'), ('F', 'Failure'), ('S', 'Success'), ('W', 'Waiting'), ('I', 'Incomplete'), ('L', 'Lost'), ('E', 'Revoked')], db_index=True, default='P', max_length=1),
        ),
    ]
