# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-19 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0003_auto_20160911_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='retries',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
