# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0004_task_retries'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_retry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
