# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0006_task_force_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='cq.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='waiting_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cq.Task'),
        ),
    ]
